<?php
/*
Plugin Name: Pojo Accessibility
Plugin URI: http://pojo.me/
Description: This plugin implements the accessibility tools for themes by Pojo Framework
Author: Pojo Team
Author URI: http://pojo.me/
Version: 1.0.2
Text Domain: pojo-accessibility
Domain Path: /languages/
*/



/**
 * Implements hook_init().
 */

function da11y_init() {
	drupal_add_css(drupal_get_path('module', 'da11y') . '/assets/css/style.css');
	drupal_add_js(drupal_get_path('module', 'da11y') . '/assets/js/app.dev.js');
}



